import java.io.*;
import java.util.*;
public class StartFrame extends javax.swing.JFrame {
    Player[] pl = new Player[30]; //max allowed is 30 ppl
    /**
     * Creates new form StartFrame
     */
    public StartFrame() {
        initComponents();
        File(); //read from file
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GRU = new javax.swing.JLabel();
        ViewPlayers = new javax.swing.JButton();
        AddPlayer = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        BBallTeam = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        HomeOfTheBears = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GRU.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        GRU.setForeground(new java.awt.Color(255, 255, 255));
        GRU.setText("Grand Ridge University  ");
        getContentPane().add(GRU, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        ViewPlayers.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ViewPlayers.setText("View Players");
        ViewPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewPlayersActionPerformed(evt);
            }
        });
        getContentPane().add(ViewPlayers, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 200, 40));

        AddPlayer.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        AddPlayer.setText("Add Players");
        AddPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPlayerActionPerformed(evt);
            }
        });
        getContentPane().add(AddPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 200, 40));

        Exit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Exit.setText("Exit");
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 200, 40));

        BBallTeam.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        BBallTeam.setForeground(new java.awt.Color(255, 255, 255));
        BBallTeam.setText("Basketball Team");
        getContentPane().add(BBallTeam, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/basketball/Bear Basketball IA.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 210));

        HomeOfTheBears.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        HomeOfTheBears.setForeground(new java.awt.Color(204, 153, 0));
        HomeOfTheBears.setText("Home of the Bears");
        getContentPane().add(HomeOfTheBears, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/basketball/1.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(700, 400));
        jLabel2.setMinimumSize(new java.awt.Dimension(700, 400));
        jLabel2.setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        setSize(new java.awt.Dimension(716, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void File(){
        File temp = new File("Players");
        if(temp.exists()== true){ //if the file is there
            //if the file exists, read it it into the arraylist of users
            try
            {
                FileInputStream fis = new FileInputStream("Players");
                ObjectInputStream ois = new ObjectInputStream(fis);
                pl = (Player[]) ois.readObject();
                ois.close();
                fis.close();
            }catch(IOException ioe){
                ioe.printStackTrace();
                return;
            }catch(ClassNotFoundException c){
                System.out.println("Class not found");
                c.printStackTrace();
                return;
            }
            //for(int i = 0; i< pl.length; i++)
                //System.out.println(pl[i]);//works
        }else{
            pl[0] = new Player("Anthony", "Davis", 45, 23, 12, 17, "Forward", 36); //if the file isn't there
            
          /*boolean found = false;
            int index = 0; //has to be 0 to 29
            if(isEmpty(pl) == false){
                while(found == false){
                    if(index >= 0 && index <= 29 ){
                        if(pl[index] == null){
                            pl[index] = new Player("Anthony", "Davis", 45, 23, 12, 17, "Forward", 36); //if the file isn't there
                            found = true;
                        }
                    }
                } 
            }*/
        }
    }

    private void AddPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPlayerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        newPlayer ne = new newPlayer(pl);
        ne.setVisible(true);
    }//GEN-LAST:event_AddPlayerActionPerformed

    private void ViewPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewPlayersActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ViewPlayers vp = new ViewPlayers(pl);
        vp.setVisible(true);
    }//GEN-LAST:event_ViewPlayersActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        
        //write to file and then close
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPlayer;
    private javax.swing.JLabel BBallTeam;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel GRU;
    private javax.swing.JLabel HomeOfTheBears;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton ViewPlayers;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
