
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.io.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tanim
 */
public class updateInfo extends javax.swing.JFrame {

    /**
     * Creates new form updateInfo
     */
    Player[] ppl;
    Player temp = null;
    public updateInfo(){
        initComponents();
    }
    public updateInfo(Player [] p, Player t) {
        ppl = p;
        temp = t;
        initComponents();
        updateScreen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GRU = new javax.swing.JLabel();
        BBallTeam = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        name2 = new javax.swing.JTextField();
        numb = new javax.swing.JTextField();
        pt = new javax.swing.JTextField();
        ast = new javax.swing.JTextField();
        rb = new javax.swing.JTextField();
        gms = new javax.swing.JTextField();
        newGms = new javax.swing.JTextField();
        FName = new javax.swing.JLabel();
        LName = new javax.swing.JLabel();
        Position = new javax.swing.JLabel();
        Number = new javax.swing.JLabel();
        GmsPlayed = new javax.swing.JLabel();
        Points = new javax.swing.JLabel();
        Assists = new javax.swing.JLabel();
        Rebounds = new javax.swing.JLabel();
        newReb = new javax.swing.JTextField();
        newAst = new javax.swing.JTextField();
        pts = new javax.swing.JTextField();
        nu = new javax.swing.JTextField();
        posit = new javax.swing.JTextField();
        newName2 = new javax.swing.JTextField();
        newName1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        posCombo = new javax.swing.JComboBox<>();
        UpdateInfo = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GRU.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        GRU.setForeground(new java.awt.Color(255, 255, 255));
        GRU.setText("Grand Ridge University  ");
        getContentPane().add(GRU, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        BBallTeam.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        BBallTeam.setForeground(new java.awt.Color(255, 255, 255));
        BBallTeam.setText("Basketball Team");
        getContentPane().add(BBallTeam, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        name1.setEditable(false);
        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 100, -1));

        name2.setEditable(false);
        getContentPane().add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 100, -1));

        numb.setEditable(false);
        getContentPane().add(numb, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 100, -1));

        pt.setEditable(false);
        getContentPane().add(pt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 100, -1));

        ast.setEditable(false);
        getContentPane().add(ast, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 100, -1));

        rb.setEditable(false);
        getContentPane().add(rb, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 100, -1));

        gms.setEditable(false);
        getContentPane().add(gms, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 100, -1));

        newGms.setBackground(new java.awt.Color(204, 204, 204));
        newGms.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newGmsKeyTyped(evt);
            }
        });
        getContentPane().add(newGms, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 100, -1));

        FName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        FName.setForeground(new java.awt.Color(255, 255, 255));
        FName.setText("First Name:");
        getContentPane().add(FName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 30));

        LName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LName.setForeground(new java.awt.Color(255, 255, 255));
        LName.setText("Last Name:");
        getContentPane().add(LName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        Position.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Position.setForeground(new java.awt.Color(255, 255, 255));
        Position.setText("Position:");
        getContentPane().add(Position, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, 20));

        Number.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Number.setForeground(new java.awt.Color(255, 255, 255));
        Number.setText("Number:");
        getContentPane().add(Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 70, 20));

        GmsPlayed.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        GmsPlayed.setForeground(new java.awt.Color(255, 255, 255));
        GmsPlayed.setText("Gms Played:");
        getContentPane().add(GmsPlayed, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        Points.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Points.setForeground(new java.awt.Color(255, 255, 255));
        Points.setText("Points:");
        getContentPane().add(Points, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        Assists.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Assists.setForeground(new java.awt.Color(255, 255, 255));
        Assists.setText("Assists:");
        getContentPane().add(Assists, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        Rebounds.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Rebounds.setForeground(new java.awt.Color(255, 255, 255));
        Rebounds.setText("Rebounds:");
        getContentPane().add(Rebounds, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        newReb.setBackground(new java.awt.Color(204, 204, 204));
        newReb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newRebKeyTyped(evt);
            }
        });
        getContentPane().add(newReb, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 100, -1));

        newAst.setBackground(new java.awt.Color(204, 204, 204));
        newAst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newAstKeyTyped(evt);
            }
        });
        getContentPane().add(newAst, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 100, -1));

        pts.setBackground(new java.awt.Color(204, 204, 204));
        pts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ptsKeyTyped(evt);
            }
        });
        getContentPane().add(pts, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 100, -1));

        nu.setBackground(new java.awt.Color(204, 204, 204));
        nu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nuKeyTyped(evt);
            }
        });
        getContentPane().add(nu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 100, -1));

        posit.setEditable(false);
        getContentPane().add(posit, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 100, -1));

        newName2.setBackground(new java.awt.Color(204, 204, 204));
        newName2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newName2KeyTyped(evt);
            }
        });
        getContentPane().add(newName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 100, -1));

        newName1.setBackground(new java.awt.Color(204, 204, 204));
        newName1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                newName1KeyTyped(evt);
            }
        });
        getContentPane().add(newName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 100, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Old Info");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("New Info");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        posCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/A", "Forward", "Guard" }));
        getContentPane().add(posCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 100, -1));

        UpdateInfo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        UpdateInfo.setText("Update Info");
        UpdateInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateInfoActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 110, -1));

        Cancel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/basketball/1.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        setSize(new java.awt.Dimension(716, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void updateScreen(){
        name1.setText(temp.fName);
        name2.setText(temp.lName);
        posit.setText(temp.position);
        numb.setText(""+temp.jerseyNumber);
        pt.setText(""+temp.points);
        ast.setText(""+temp.assist);
        rb.setText(""+temp.rebounds);
        gms.setText(""+temp.totalGames);
    }
    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ViewPlayers pg = new ViewPlayers(ppl);
        pg.setVisible(true);
    }//GEN-LAST:event_CancelActionPerformed

    private void UpdateInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateInfoActionPerformed
        // TODO add your handling code here:
        String name1 = newName1.getText();
        String name2 = newName2.getText();
        String position = (String) posCombo.getSelectedItem();
        int number = 0;
        int points = 0;
        int assists = 0;
        int rebounds = 0;
        int gmsPlayed = 0;
        if(!nu.getText().equals("")){
            if(!pts.getText().equals("")){
                if(!newAst.getText().equals("")){
                    if(!newReb.getText().equals("")){
                        if(!newGms.getText().equals("")){
                            number = Integer.parseInt(nu.getText());
                            points = Integer.parseInt(pts.getText());
                            assists = Integer.parseInt(newAst.getText());
                            rebounds = Integer.parseInt(newReb.getText());
                            gmsPlayed = Integer.parseInt(newGms.getText());
                        }
                    }
                }
            }
        }
        boolean updatePlayer = true;
        if(name1.equals("") || name2.equals("")||position.equals("N/A")||nu.getText().equals("")|| pts.getText().equals("")||newAst.getText().equals("")||newReb.getText().equals("")||newGms.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please input all fields"); 
            updatePlayer = false;
        }
        if(updatePlayer == true){
            for(int i = 0; i< ppl.length; i++){
                if(ppl[i] != null){
                    if(ppl[i].fName.equals(temp.fName) && ppl[i].lName.equals(temp.lName)){
                        ppl[i] = new Player(name1, name2, gmsPlayed, number, rebounds, assists, position, points);
                        JOptionPane.showMessageDialog(null, "The Player's Stats have been updated."); 
                        //update the file and go back to screen 
                        try{
                            FileOutputStream fos= new FileOutputStream("Players");
                            ObjectOutputStream oos= new ObjectOutputStream(fos);
                            oos.writeObject(ppl); //this is a way to store the arraylist in a file
                            oos.close();
                            fos.close();
                        }catch(IOException ioe){
                            ioe.printStackTrace();
                        }
                        
                        this.setVisible(false);
                        ViewPlayers plt = new ViewPlayers(ppl);
                        plt.setVisible(true);
                    }
                }
            }
        }
    }//GEN-LAST:event_UpdateInfoActionPerformed

    private void newName1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newName1KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) ||  (c==KeyEvent.VK_BACK_SPACE)||  c==KeyEvent.VK_DELETE ))
            evt.consume();
    }//GEN-LAST:event_newName1KeyTyped

    private void newName2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newName2KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) ||  (c==KeyEvent.VK_BACK_SPACE)||  c==KeyEvent.VK_DELETE ))
            evt.consume();
    }//GEN-LAST:event_newName2KeyTyped

    private void nuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nuKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE){
            evt.consume();
        }
    }//GEN-LAST:event_nuKeyTyped

    private void ptsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ptsKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE){
            evt.consume();
        }
    }//GEN-LAST:event_ptsKeyTyped

    private void newAstKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newAstKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE){
            evt.consume();
        }
    }//GEN-LAST:event_newAstKeyTyped

    private void newRebKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newRebKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE){
            evt.consume();
        }
    }//GEN-LAST:event_newRebKeyTyped

    private void newGmsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newGmsKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE){
            evt.consume();
        }
    }//GEN-LAST:event_newGmsKeyTyped

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Assists;
    private javax.swing.JLabel BBallTeam;
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel FName;
    private javax.swing.JLabel GRU;
    private javax.swing.JLabel GmsPlayed;
    private javax.swing.JLabel LName;
    private javax.swing.JLabel Number;
    private javax.swing.JLabel Points;
    private javax.swing.JLabel Position;
    private javax.swing.JLabel Rebounds;
    private javax.swing.JButton UpdateInfo;
    private javax.swing.JTextField ast;
    private javax.swing.JTextField gms;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField name2;
    private javax.swing.JTextField newAst;
    private javax.swing.JTextField newGms;
    private javax.swing.JTextField newName1;
    private javax.swing.JTextField newName2;
    private javax.swing.JTextField newReb;
    private javax.swing.JTextField nu;
    private javax.swing.JTextField numb;
    private javax.swing.JComboBox<String> posCombo;
    private javax.swing.JTextField posit;
    private javax.swing.JTextField pt;
    private javax.swing.JTextField pts;
    private javax.swing.JTextField rb;
    // End of variables declaration//GEN-END:variables
}
